"""updated fields migration

Revision ID: 1794a905be7d
Revises: 7d9bc0e41c08
Create Date: 2024-10-21 12:54:26.188281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1794a905be7d'
down_revision: Union[str, None] = '7d9bc0e41c08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column('users', sa.Column('company', sa.String(), nullable=True))
    op.add_column('users', sa.Column('geography_of_hq', sa.String(), nullable=True))
    op.add_column('users', sa.Column('company_size', sa.String(), nullable=True))
    op.add_column('users', sa.Column('company_address', sa.String(), nullable=True))
    op.add_column('users', sa.Column('company_number', sa.String(), nullable=True))
    op.add_column('users', sa.Column('terms_and_conditions_accepted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'terms_and_conditions_accepted')
    op.drop_column('users', 'company_number')
    op.drop_column('users', 'company_address')
    op.drop_column('users', 'company_size')
    op.drop_column('users', 'geography_of_hq')
    op.drop_column('users', 'company')
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###
